// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMatchData, CreateMatchErrors, CreateMatchResponses, CreatePlayerData, CreatePlayerErrors, CreatePlayerResponses, GetHealthData, GetHealthResponses, GetLeaderboardData, GetLeaderboardResponses, ListMatchesData, ListMatchesResponses, ListPlayersData, ListPlayersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List all players
 */
export const listPlayers = <ThrowOnError extends boolean = false>(options?: Options<ListPlayersData, ThrowOnError>) => (options?.client ?? client).get<ListPlayersResponses, unknown, ThrowOnError>({ url: '/players', ...options });

/**
 * Create a player
 */
export const createPlayer = <ThrowOnError extends boolean = false>(options: Options<CreatePlayerData, ThrowOnError>) => (options.client ?? client).post<CreatePlayerResponses, CreatePlayerErrors, ThrowOnError>({
    url: '/players',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all matches
 */
export const listMatches = <ThrowOnError extends boolean = false>(options?: Options<ListMatchesData, ThrowOnError>) => (options?.client ?? client).get<ListMatchesResponses, unknown, ThrowOnError>({ url: '/matches', ...options });

/**
 * Record a match result
 */
export const createMatch = <ThrowOnError extends boolean = false>(options: Options<CreateMatchData, ThrowOnError>) => (options.client ?? client).post<CreateMatchResponses, CreateMatchErrors, ThrowOnError>({
    url: '/matches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get aggregated player standings
 */
export const getLeaderboard = <ThrowOnError extends boolean = false>(options?: Options<GetLeaderboardData, ThrowOnError>) => (options?.client ?? client).get<GetLeaderboardResponses, unknown, ThrowOnError>({ url: '/leaderboard', ...options });
