// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HealthResponse = {
    status: 'ok';
};

export type ErrorResponse = {
    message: string;
};

export type Player = {
    id: string;
    name: string;
    createdAt: string;
};

export type CreatePlayerRequest = {
    name: string;
};

export type MatchSide = {
    player1Id: string;
    player2Id?: string | null;
};

export type Match = {
    id: string;
    left: MatchSide;
    right: MatchSide;
    leftScore: number;
    rightScore: number;
    playedAt: string;
    createdAt: string;
};

export type CreateMatchRequest = {
    left: MatchSide;
    right: MatchSide;
    leftScore: number;
    rightScore: number;
    playedAt: string;
};

export type LeaderboardEntry = {
    playerId: string;
    playerName: string;
    matches: number;
    wins: number;
    losses: number;
    goalsFor: number;
    goalsAgainst: number;
    goalDifference: number;
};

export type PlayersResponse = {
    items: Array<Player>;
};

export type MatchesResponse = {
    items: Array<Match>;
};

export type LeaderboardResponse = {
    items: Array<LeaderboardEntry>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy.
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListPlayersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/players';
};

export type ListPlayersResponses = {
    /**
     * Players in creation order.
     */
    200: PlayersResponse;
};

export type ListPlayersResponse = ListPlayersResponses[keyof ListPlayersResponses];

export type CreatePlayerData = {
    body: CreatePlayerRequest;
    path?: never;
    query?: never;
    url: '/players';
};

export type CreatePlayerErrors = {
    /**
     * Invalid input.
     */
    400: ErrorResponse;
};

export type CreatePlayerError = CreatePlayerErrors[keyof CreatePlayerErrors];

export type CreatePlayerResponses = {
    /**
     * Player created.
     */
    201: Player;
};

export type CreatePlayerResponse = CreatePlayerResponses[keyof CreatePlayerResponses];

export type ListMatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/matches';
};

export type ListMatchesResponses = {
    /**
     * Matches in reverse chronological order.
     */
    200: MatchesResponse;
};

export type ListMatchesResponse = ListMatchesResponses[keyof ListMatchesResponses];

export type CreateMatchData = {
    body: CreateMatchRequest;
    path?: never;
    query?: never;
    url: '/matches';
};

export type CreateMatchErrors = {
    /**
     * Invalid input.
     */
    400: ErrorResponse;
};

export type CreateMatchError = CreateMatchErrors[keyof CreateMatchErrors];

export type CreateMatchResponses = {
    /**
     * Match created.
     */
    201: Match;
};

export type CreateMatchResponse = CreateMatchResponses[keyof CreateMatchResponses];

export type GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leaderboard';
};

export type GetLeaderboardResponses = {
    /**
     * Standings derived from all logged matches.
     */
    200: LeaderboardResponse;
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];
